name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "1 */12 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Sync boydaihungst/msbuild-project-tools-server upstream
        env:
          # This MUST be a PAT with 'repo' scope for Repo B
          EXTERNAL_TOKEN: ${{ secrets.RW_GITHUB_TOKEN }}
        run: |
          # 1. Authenticate the GH CLI for the external repo
          echo "${EXTERNAL_TOKEN}" | gh auth login --with-token

          # 2. Trigger the sync on Repo B
          # Format: owner_B/repo_B
          gh repo sync "boydaihungst/msbuild-project-tools-server" --branch master

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.RW_GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "Huy Hoang"
          git config user.email "boydaihungs@gmail.com"
          git config http.sslVerify false

      - name: Update package.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.RW_GITHUB_TOKEN }}
        working-directory: packages
        run: |
          LATEST_COMMIT_DATE=$(gh api repos/tintoy/msbuild-project-tools-server/commits/HEAD \
                                --jq '.commit.committer.date' | \
                                xargs -I{} date -d "{}" +%Y.%m.%d)

          echo "Latest date found: $LATEST_COMMIT_DATE"

          sed -i "s|msbuild-project-tools-server@.*|msbuild-project-tools-server@${LATEST_COMMIT_DATE}|" msbuild_project_tools_server/package.yaml

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.RW_GITHUB_TOKEN }}
        run: |
          # Use git status --porcelain for more reliable change detection
          if [ -n "$(git status --porcelain)" ]; then
            echo "detected changes"
            git add packages/
            git commit -m "Daily updates"
            git push origin HEAD

          else
            echo "No updates detected. Skipping commit."
          fi
