name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "1 */12 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "Huy Hoang"
          git config user.email "boydaihungs@gmail.com"
          git config http.sslVerify false

      - name: Update package.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: packages
        run: |
          LATEST_COMMIT_DATE=$(gh api repos/tintoy/msbuild-project-tools-server/commits/HEAD \
                                --jq '.commit.committer.date' | \
                                xargs -I{} date -d "{}" +%Y.%m.%d)

          echo "Latest date found: $LATEST_COMMIT_DATE"

          sed -i "s|msbuild-project-tools-server@.*|msbuild-project-tools-server@${LATEST_COMMIT_DATE}|" msbuild_project_tools/package.yaml

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use git status --porcelain for more reliable change detection
          if [ -n "$(git status --porcelain)" ]; then
            echo "detected changes"
            git add packages/
            git commit -m "Daily updates"
            git push origin HEAD
          else
            echo "No updates detected. Skipping commit."
          fi
